### ISSUE TITLE
API change?

### ISSUE THREAD

**Issue by killswitch-GUI** [viraptor/wigle#2]
API change?

```
>>> import wigle
>> >w = wigle.Wigle('******','******')
>> >w.search(ssid="foobar")
      Traceback (most recent call last):
       File "<stdin>", line 1, in <module>
 File "/usr/local/lib/python2.7/dist-packages/wigle-0.0.4-py2.7.egg/wigle/__init__.py", line 153, in search
    data = resp.json()
TypeError: 'dict' object is not callable
```

**Comment by killswitch-GUI** [comment]
I also hand checked to make sure i wasn't being dumb.

First Check URL:

```
https://wigle.net/api/v1/jsonSearch?netid=00:22:55:DF:C8:01
```

I got this output:

```
{"resultCount":1,"results":[{"qos":"0","trilong":"-87.60340118","wep":"N","transid":"20101228-00171","channel":"11","visible":"Y","lasttime":"2010-12-28 23:03:19","trilat":"41.89127731","freenet":"?","bcninterval":null,"lastupdt":"20101228230351","paynet":"Y","name":null,"userfound":false,"type":"infra","comment":null,"firsttime":"2010-12-28 18:21:52","discoverer":"bobzilla","netid":"00:22:55:df:c8:01","flags":null,"ssid":"Navypier"}],"last":1,"first":1,"success":true}
```

**Comment by killswitch-GUI** [comment]
I just came across this and got it to work funny enough.

This didn't for some reason:

```
pip install --upgrade requests 

Requirement already satisfied (use --upgrade to upgrade): requests in /usr/lib/python2.7/dist-packages
Cleaning up...

```

This worked:

```
sudo pip install --upgrade requests 
Downloading/unpacking requests from https://pypi.python.org/packages/source/r/requests/requests-2.7.0.tar.gz#md5=29b173fd5fa572ec0764d1fd7b527260
  Downloading requests-2.7.0.tar.gz (451Kb): 451Kb downloaded
  Running setup.py egg_info for package requests

Installing collected packages: requests
  Found existing installation: requests 0.12.1
    Uninstalling requests:
      Successfully uninstalled requests
  Running setup.py install for requests

Successfully installed requests
Cleaning up...

```

**Comment by viraptor** [comment]
Python 2.x is not supported for wigle, so it may work by accident, or may explode. Please check on python 3.x.

I just checked and the API is till compatible - search worked as expected.
